const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const adController = require('../controllers/adController');
const { authenticate, authorize } = require('../middleware/auth');
const validate = require('../middleware/validate');
const { createUserRules, updateUserRules, userListRules, userIdParamRules } = require('../validators/userValidators');
const { adListRules, createAdRules, updateAdRules, adIdParamRules } = require('../validators/adValidators');
router.use(authenticate);
router.use(authorize('admin','super_admin'));
router.get('/overview', adminController.getOverview.bind(adminController));
router.get('/users', userListRules, validate, adminController.getUsers.bind(adminController));
router.post('/users', createUserRules, validate, adminController.createUser.bind(adminController));
router.put('/users/:id', updateUserRules, validate, adminController.updateUser.bind(adminController));
router.delete('/users/:id', userIdParamRules, validate, adminController.deleteUser.bind(adminController));
router.get('/ads', adListRules, validate, adController.listAds.bind(adController));
router.post('/ads', authorize('super_admin'), createAdRules, validate, adController.createAd.bind(adController));
router.put('/ads/:id', updateAdRules, validate, adController.updateAd.bind(adController));
router.delete('/ads/:id', authorize('super_admin'), adIdParamRules, validate, adController.deleteAd.bind(adController));
router.get('/settings', adminController.getSettings.bind(adminController));
router.put('/settings', adminController.updateSettings.bind(adminController));
router.post('/settings', adminController.updateSettings.bind(adminController));
module.exports = router;
