const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Article = sequelize.define('Article', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  title: { type: DataTypes.STRING(200), allowNull: false },
  slug: { type: DataTypes.STRING(250), allowNull: false, unique: true },
  subtitle: { type: DataTypes.STRING(300), allowNull: true },
  excerpt: { type: DataTypes.TEXT, allowNull: true },
  content: { type: DataTypes.TEXT('long'), allowNull: false },
  contentPlainText: { type: DataTypes.TEXT('long'), allowNull: true },
  authorId: { type: DataTypes.UUID, allowNull: false },
  featuredImageId: { type: DataTypes.UUID, allowNull: true },
  mediaGallery: { type: DataTypes.JSONB, defaultValue: [] },
  videoUrl: { type: DataTypes.STRING(500), allowNull: true },
  videoEmbed: { type: DataTypes.TEXT, allowNull: true },
  metaTitle: { type: DataTypes.STRING(70), allowNull: true },
  metaDescription: { type: DataTypes.STRING(160), allowNull: true },
  metaKeywords: { type: DataTypes.ARRAY(DataTypes.STRING), defaultValue: [] },
  seoScore: { type: DataTypes.INTEGER, defaultValue: 0 },
  seoAnalysis: { type: DataTypes.JSONB, defaultValue: {} },
  canonicalUrl: { type: DataTypes.STRING(500), allowNull: true },
  ogImage: { type: DataTypes.STRING(500), allowNull: true },
  ogTitle: { type: DataTypes.STRING(95), allowNull: true },
  ogDescription: { type: DataTypes.STRING(200), allowNull: true },
  twitterCard: { type: DataTypes.ENUM('summary', 'summary_large_image', 'app', 'player'), defaultValue: 'summary_large_image' },
  schemaMarkup: { type: DataTypes.JSONB, defaultValue: {} },
  readTime: { type: DataTypes.INTEGER, defaultValue: 0 },
  wordCount: { type: DataTypes.INTEGER, defaultValue: 0 },
  status: { type: DataTypes.ENUM('draft', 'pending', 'published', 'scheduled', 'archived', 'trash'), defaultValue: 'draft' },
  publishedAt: { type: DataTypes.DATE, allowNull: true },
  scheduledFor: { type: DataTypes.DATE, allowNull: true },
  isFeatured: { type: DataTypes.BOOLEAN, defaultValue: false },
  isBreaking: { type: DataTypes.BOOLEAN, defaultValue: false },
  isPinned: { type: DataTypes.BOOLEAN, defaultValue: false },
  isSponsored: { type: DataTypes.BOOLEAN, defaultValue: false },
  allowComments: { type: DataTypes.BOOLEAN, defaultValue: true },
  rssIncluded: { type: DataTypes.BOOLEAN, defaultValue: true },
  msnEligible: { type: DataTypes.BOOLEAN, defaultValue: false },
  msnSubmitted: { type: DataTypes.BOOLEAN, defaultValue: false },
  msnStatus: { type: DataTypes.ENUM('not_submitted', 'pending', 'approved', 'rejected'), defaultValue: 'not_submitted' },
  views: { type: DataTypes.INTEGER, defaultValue: 0 },
  uniqueViews: { type: DataTypes.INTEGER, defaultValue: 0 },
  shares: { type: DataTypes.JSONB, defaultValue: { total: 0, facebook: 0, twitter: 0, linkedin: 0 } },
  likes: { type: DataTypes.INTEGER, defaultValue: 0 },
  commentsCount: { type: DataTypes.INTEGER, defaultValue: 0 },
  version: { type: DataTypes.INTEGER, defaultValue: 1 },
  revisionHistory: { type: DataTypes.JSONB, defaultValue: [] },
  customFields: { type: DataTypes.JSONB, defaultValue: {} },
  template: { type: DataTypes.ENUM('default', 'full_width', 'sidebar', 'magazine', 'video', 'gallery'), defaultValue: 'default' },
}, {
  timestamps: true,
  paranoid: true,
  tableName: 'Articles',
  indexes: [
    { fields: ['slug'], unique: true },
    { fields: ['status'] },
    { fields: ['authorId'] },
    { fields: ['publishedAt'] },
    { fields: ['isFeatured'] },
  ],
});

module.exports = Article;